#配置注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#      修改application的自定义路径名
  instance:
    hostname: clientName
spring:
  application:
#  修改appliction 的名字
    name: client