spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jason1215/config-repo
          username: jason1215
          password: jason1215gitee
          basedir: /Users/jason/code/myProjects/java/SpringCloud_Sell/config/basedir

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#      expose: "*"



#19.5.8
#spring:
#  application:
#    name: config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/jason1215/config-repo
#          username: jason1215
#          password: jason1215gitee
#          basedir: /Users/jason/code/myProjects/java/SpringCloud_Sell/config/basedir
#
#eureka:
#  client:
#    service-url:
#     defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
#
#  instance:
#    prefer-ip-address: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
##      expose: "*"


