eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/
#      defaultZone: http://localhost:8762/eureka/
  #    register-with-eureka: false

  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8762/eureka/
##      defaultZone: http://eureka2:8762/eureka/
##    register-with-eureka: false
#  instance:
#    prefer-ip-address: true
#spring:
#  application:
#    name: eureka
#server:
#  port: 8761



#19.5.8
#eureka:
#  client:
#    service-url:
#      #      defaultZone: http://eureka2:8762/eureka/
#      defaultZone: http://localhost:8762/eureka/
#    #    register-with-eureka: false
#    instance:
#      prefer-ip-address: true
#  server:
#    enable-self-preservation: false
#spring:
#  application:
#    name: eureka
#server:
#  port: 8761


